### ISSUE TITLE
Compatibility with Python 3.9?

### ISSUE THREAD

**Issue by JPereira-FJB** [Merck/BioPhi#36]
Hi. I'm attempting to install biophi using conda on an environment using Python 3.9. I know that in the environment from the instructions it specifically says to use Python 3.8. I was wondering if there's any plans to assure compatibility with Python 3.9 any time soon. Thank you.

```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                  

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31
```

**Comment by JPereira-FJB** [comment]
Thanks, @prihoda !

I'll try it out once it merges. 

Another unrelated question: from the docker-compose.yml, I can change the port of both the web service and the redis cache the celery workers are connected to. I'm using this to connect to my Redis cache running locally, outside the container. It works great if they subscribe to database 0. It fails (error bellow) if I change the database number to 1 or 2 (or even 1 for task queue and 2 for results cache). Is it possible to change this somehow?

```
worker_1  | [2023-05-17 09:55:19,967: CRITICAL/MainProcess] Can't decode message body: ContentDisallowed('Refusing to deserialize untrusted content of type json (application/json)') [type:'application/json' encoding:'utf-8' headers:{'clock': 279, 'expires': 1684317320.9657383}]
worker_1  | 
worker_1  | body: b'{"method": "enable_events", "arguments": {}, "destination": null, "pattern": null, "matcher": null}' (99b)
worker_1  | Traceback (most recent call last):
worker_1  |   File "/opt/conda/lib/python3.8/site-packages/kombu/messaging.py", line 620, in _receive_callback
worker_1  |     decoded = None if on_m else message.decode()
worker_1  |   File "/opt/conda/lib/python3.8/site-packages/kombu/message.py", line 194, in decode
worker_1  |     self._decoded_cache = self._decode()
worker_1  |   File "/opt/conda/lib/python3.8/site-packages/kombu/message.py", line 198, in _decode
worker_1  |     return loads(self.body, self.content_type,
worker_1  |   File "/opt/conda/lib/python3.8/site-packages/kombu/serialization.py", line 242, in loads
worker_1  |     raise self._for_untrusted_content(content_type, 'untrusted')
worker_1  | kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type json (application/json)
```
